# Generated by Django 4.2.7 on 2023-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_nodemodel_ex_ip_alter_nodemodel_in_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemodel',
            name='EX_IP',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='nodemodel',
            name='IN_IP',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
