# Generated by Django 4.2.7 on 2023-12-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodel',
            name='local_connection',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
