# Generated by Django 4.2.7 on 2023-12-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_nodemodel_local_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodel',
            name='access_token',
            field=models.CharField(default='123123123123123123', max_length=256),
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='refresh_token',
            field=models.CharField(default='123123123123123123', max_length=256),
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='secret_key',
            field=models.CharField(default='123123123123123123', max_length=64),
        ),
        migrations.AlterField(
            model_name='nodemodel',
            name='UUID',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
