# Generated by Django 4.2.7 on 2023-12-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_nodemodel_access_token_nodemodel_refresh_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodemodel',
            old_name='access_token',
            new_name='local_server_access_token',
        ),
        migrations.RenameField(
            model_name='nodemodel',
            old_name='refresh_token',
            new_name='local_server_refresh_token',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='access_token',
            new_name='user_access_token',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='refresh_token',
            new_name='user_refresh_token',
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='node_access_token',
            field=models.CharField(default='123123123123123123', max_length=256),
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='node_refresh_token',
            field=models.CharField(default='123123123123123123', max_length=256),
        ),
    ]
