# Generated by Django 4.2.8 on 2024-01-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_rename_access_token_nodemodel_local_server_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_key', models.CharField(default='personal_key', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='nodemodel',
            name='local_server_access_token',
            field=models.CharField(default='local_server_access_token', max_length=256),
        ),
        migrations.AlterField(
            model_name='nodemodel',
            name='local_server_refresh_token',
            field=models.CharField(default='local_server_refresh_token', max_length=256),
        ),
        migrations.AlterField(
            model_name='nodemodel',
            name='node_access_token',
            field=models.CharField(default='node_access_token', max_length=256),
        ),
        migrations.AlterField(
            model_name='nodemodel',
            name='node_refresh_token',
            field=models.CharField(default='node_refresh_token', max_length=256),
        ),
        migrations.AlterField(
            model_name='nodemodel',
            name='secret_key',
            field=models.CharField(default='secret_key', max_length=64),
        ),
    ]
