# Generated by Django 4.2.8 on 2024-01-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_serverdatamodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouduser',
            name='secret_key',
            field=models.CharField(default='secret_key', max_length=64),
        ),
        migrations.AddField(
            model_name='clouduser',
            name='user_access_token',
            field=models.CharField(default='user_access_token', max_length=256),
        ),
        migrations.AddField(
            model_name='clouduser',
            name='user_refresh_token',
            field=models.CharField(default='user_refresh_token', max_length=256),
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
