# Generated by Django 4.2.8 on 2024-01-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_clouduser_secret_key_clouduser_user_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clouduser',
            name='secret_key',
        ),
        migrations.RemoveField(
            model_name='clouduser',
            name='user_access_token',
        ),
        migrations.RemoveField(
            model_name='clouduser',
            name='user_refresh_token',
        ),
        migrations.RemoveField(
            model_name='nodemodel',
            name='local_server_access_token',
        ),
        migrations.RemoveField(
            model_name='nodemodel',
            name='local_server_refresh_token',
        ),
    ]
