# Generated by Django 4.2.11 on 2024-03-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_clouduser_user_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodemodel',
            name='local_connection',
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='port',
            field=models.CharField(default='False', max_length=5, unique=True),
        ),
    ]
