"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/ """
import os, json
from pathlib import Path

from django.urls import reverse_lazy

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "192.168.0.98",
    "176.197.34.213",
    "whoole.space",
    "www.whoole.space",
    "home.whoole.space",
]

CSRF_TRUSTED_ORIGINS = [
    "https://localhost",
    "http://localhost",
    "https://whoole.space",
    "http://whoole.space",
    "https://www.whoole.space",
    "http://www.whoole.space",
    "https://home.whoole.space",
    "http://home.whoole.space",
    "http://192.168.0.98",
    "http://176.197.34.213",
    "https://192.168.0.98",
    "https://176.197.34.213",
]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f790b_syh@as9^%j(e290_k8mgsq=7mgznh^g0eu(231#w+j!l"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

#DATA_UPLOAD_MAX_MEMORY_SIZE = 1000000

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "MainApp.apps.MainConfig",
    "crispy_forms",
    "crispy_bootstrap5",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",  # 1
    "django.contrib.messages.middleware.MessageMiddleware",  # 2
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # 3
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
]

#CORS_ALLOWED_ORIGINS = [
#    "https://192.168.0.81:8002",
#    "http://192.168.0.81:8002",
#    "http://localhost",
#]
#
#SECURE_REFERRER_POLICY = 'no-referrer'

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "django_project",
        "PASSWORD": "djangoisme",
        "USER": "django_user",
        "HOST": "/var/run/postgresql",
        "PORT": "",
    }
}


CACHES = {
   'default': {
       'BACKEND': 'django_redis.cache.RedisCache',
       'LOCATION': 'redis://localhost:6379/0',
       'OPTIONS': {
           'CLIENT_CLASS': 'django_redis.client.DefaultClient',
           'PASSWORD': 'redisisme',
           'CONNECTION_POOL_KWARGS': {'max_connections': 100},
       }
   }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "MainApp/templates/static/")
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "MainApp/templates/static/"),
#]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = reverse_lazy("MainApp:login")
LOGOUT_URL = reverse_lazy("MainApp:logout")
LOGIN_REDIRECT_URL = reverse_lazy("MainApp:profile")
AUTH_USER_MODEL = "MainApp.CloudUser"
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

CSRF_COOKIE_NAME = "csrftoken"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "/var/log/django/debug.log",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}


# ------------------------------------------------------------- #
#                           VARIABLES                           #
# ------------------------------------------------------------- #

# SITE_DOMAIN = os.environ.get("domain")

existExt = {
# image #
    'png': 'image-icon.png', 
    'jpeg': 'image-icon.png',
    'jpg': 'image-icon.png',
    'webp': 'image-icon.png',
    'bmp': 'image-icon.png',
    'gif': 'image-icon.png',
    'svg': 'svg-icon.png',
# music #
    'bmp': 'music-icon.svg',
    'mp2': 'music-icon.svg',
    'mp3': 'music-icon.svg',
    'wav': 'music-icon.svg',
    'flac': 'music-icon.svg',
# video #
    'mp4': 'video-icon.svg',
# txt #
    'txt': 'txt-icon.png',
# docs #
    'ppt': 'powerpoint-icon.svg',
    'doc': 'word-icon.svg',
    'xsl': 'excel-icon.svg',
    'pptx': 'powerpoint-icon.svg',
    'docx': 'word-icon.svg',
    'xslx': 'excel-icon.svg',
    'odp': 'powerpoint-icon.svg',
    'pdf': 'pdf-icon.svg',
# programming #
    'py': 'python-icon.svg',
    'exe': 'script-icon.svg',
    'sh': 'script-icon.svg',
# archives #
    'zip': 'zip-icon.png',
    'rar': 'rar-icon.svg',
}

MY_VARIABLES = {
    "existExt": json.dumps(existExt),
    "GREETINGS": "HELLO FRIEND",
}
